/*
  ! This file is automatically generated using its json variant. Change only the json file.
*/

import { JSONSchema4 } from 'json-schema';

export const OctraLoggingJSONSchema: JSONSchema4 = {
  properties: {
    version: {
      type: 'string',
    },
    encoding: {
      type: 'string',
    },
    projectname: {
      type: 'string',
    },
    logs: {
      items: {
        type: 'object',
        properties: {
          timestamp: {
            type: 'integer',
          },
          type: {
            type: 'string',
          },
          target: {
            type: 'string',
          },
          value: {
            type: ['string', 'integer', 'object'],
          },
          playpos: {
            type: 'integer',
          },
          caretpos: {
            type: 'integer',
          },
        },
      },
      type: 'array',
    },
  },
  additionalProperties: true,
};
