/*
  ! This file is automatically generated using its json variant. Change only the json file.
*/

  export const OctraProjectConfigJSONSchema = {
  '$id': 'v0.0.1',
  'type': 'object',
  'required': [
    'version'
  ],
  'properties': {
    'version': {
      'type': 'string',
      'readOnly': true
    },
    'navigation': {
      'properties': {
        'export': {
          'type': 'boolean'
        },
        'interfaces': {
          'type': 'boolean'
        },
        'help_url': {
          'type': 'string'
        }
      },
      'type': 'object'
    },
    'responsive': {
      'properties': {
        'enabled': {
          'type': 'boolean'
        },
        'fixedwidth': {
          'type': 'number'
        }
      },
      'type': 'object'
    },
    'agreement': {
      'properties': {
        'enabled': {
          'type': 'boolean'
        },
        'text': {
          'type': 'object'
        }
      },
      'type': 'object'
    },
    'plugins': {
      'type': 'object'
    },
    'languages': {
      'items': {
        'type': 'string'
      },
      'type': 'array'
    },
    'interfaces': {
      'items': {
        'type': 'string'
      },
      'type': 'array'
    },
    'feedback_form': {
      'items': {
        'properties': {
          'title': {
            'type': 'object'
          },
          'controls': {
            'items': {
              'properties': {
                'type': {
                  'type': 'string'
                },
                'name': {
                  'type': 'string'
                },
                'label': {
                  'type': 'object'
                },
                'value': {
                  'type': 'string'
                },
                'custom': {
                  'type': 'object'
                },
                'required': {
                  'type': 'boolean'
                }
              },
              'type': 'object'
            },
            'type': 'array'
          }
        },
        'type': 'object'
      },
      'type': 'array'
    },
    'octra': {
      'properties': {
        'login': {
          'properties': {
            'enabled': {
              'type': 'boolean'
            }
          },
          'type': 'object'
        },
        'showdetails': {
          'type': 'boolean'
        },
        'responsive': {
          '$id': '/properties/octra/responsive',
          'properties': {
            'enabled': {
              'type': 'boolean'
            },
            'fixedwidth': {
              'type': 'number'
            }
          },
          'type': 'object'
        },
        'bugreport': {
          'properties': {
            'enabled': {
              'type': 'boolean'
            },
            'name': {
              'type': 'string'
            },
            'auth_token': {
              'type': 'string'
            },
            'url': {
              'type': 'string'
            }
          },
          'type': 'object'
        },
        'allowed_browsers': {
          'items': {
            'properties': {
              'name': {
                'type': 'string'
              },
              'version': {
                'type': 'string'
              }
            },
            'type': 'object'
          },
          'type': 'array'
        },
        'languages': {
          'items': {
            'type': 'string'
          },
          'type': 'array'
        }
      },
      'type': 'object'
    }
  },
  'additionalProperties': true
}
;